id: P009112
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG12207
  title: དྲང་ངེས་ལེགས་བཤད་སྙིང་པོའི་དཀའ་འགྲེལ་རིན་ཆེན་སྒྲོན་མེ།
  author: ''
  volumes:
    dc7bdb857391475189c7e579d6a87d68:
      image_group_id: I1KG12264
      title: ''
      volume_number: 1
      total_pages: 322
